//! `styles/vendor/` is generated by `build.rs` from `eona-ui-toolkit`'s
//! stylesheet constants, but committed, because Trunk resolves `index.html`'s
//! `rel="css"` links before it ever invokes cargo — a file build.rs has not
//! written yet does not exist when Trunk looks for it.
//!
//! Committing generated output invites two failures, and this guards both: a
//! copy edited here instead of in the toolkit, and a copy left stale when the
//! toolkit moved on. `cargo build` regenerates them, so a red test here is
//! fixed by rebuilding and committing the result.

use std::fs;

#[test]
fn vendored_stylesheets_match_the_toolkit() {
    for (name, expected) in [
        ("tokens.css", eona_ui_toolkit::TOKENS_CSS),
        ("components.css", eona_ui_toolkit::COMPONENTS_CSS),
        ("ontology.css", eona_ui_toolkit::ONTOLOGY_CSS),
    ] {
        let path = format!("styles/vendor/{name}");
        let actual = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("{path} is missing ({e}); run `cargo build`"));
        assert_eq!(
            actual, expected,
            "{path} has drifted from the toolkit's constant. Edit the toolkit, then \
             `cargo build` to regenerate and commit the result."
        );
    }
}

#[test]
fn index_html_links_every_vendored_stylesheet() {
    let index = fs::read_to_string("index.html").expect("read index.html");
    for name in ["tokens.css", "components.css", "ontology.css"] {
        assert!(
            index.contains(&format!("styles/vendor/{name}")),
            "index.html does not link styles/vendor/{name}, so build.rs writes a file \
             nothing serves"
        );
    }
    // tokens.css defines the custom properties the other two read, so a browser
    // must see it first.
    let tokens = index.find("styles/vendor/tokens.css").expect("tokens.css link");
    for name in ["components.css", "ontology.css"] {
        let other = index.find(&format!("styles/vendor/{name}")).unwrap();
        assert!(tokens < other, "tokens.css must be linked before {name}");
    }
}
