//! `styles/vendor/` is generated by `build.rs` from `eona-ui-toolkit`'s
//! stylesheet constants, but committed, because Trunk resolves `index.html`'s
//! `rel="css"` links before it ever invokes cargo — a file build.rs has not
//! written yet does not exist when Trunk looks for it.
//!
//! Committing generated output invites two failures, and this guards both: a
//! copy edited here instead of in the toolkit, and a copy left stale when the
//! toolkit moved on. `cargo build` regenerates them, so a red test here is
//! fixed by rebuilding and committing the result.
//!
//! styles/ontology-browser.css is deliberately absent from both checks: it is
//! this app's own stylesheet for the ontology tier that came back out of the
//! toolkit, not a vendored copy of anything.

use std::fs;

#[test]
fn vendored_stylesheets_match_the_toolkit() {
    for (name, expected) in [
        ("tokens.css", eona_ui_toolkit::TOKENS_CSS),
        ("components.css", eona_ui_toolkit::COMPONENTS_CSS),
        ("ontology.css", eona_ui_toolkit::ONTOLOGY_CSS),
    ] {
        let path = format!("styles/vendor/{name}");
        let actual = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("{path} is missing ({e}); run `cargo build`"));
        assert_eq!(
            actual, expected,
            "{path} has drifted from the toolkit's constant. Edit the toolkit, then \
             `cargo build` to regenerate and commit the result."
        );
    }
}

#[test]
fn index_html_links_every_vendored_stylesheet() {
    let index = fs::read_to_string("index.html").expect("read index.html");
    for name in ["tokens.css", "components.css", "ontology.css"] {
        assert!(
            index.contains(&format!("styles/vendor/{name}")),
            "index.html does not link styles/vendor/{name}, so build.rs writes a file \
             nothing serves"
        );
    }
    // tokens.css defines the custom properties the other two read, so a browser
    // must see it first.
    let tokens = index.find("styles/vendor/tokens.css").expect("tokens.css link");
    for name in ["components.css", "ontology.css"] {
        let other = index.find(&format!("styles/vendor/{name}")).unwrap();
        assert!(tokens < other, "tokens.css must be linked before {name}");
    }
}

/// The ontology tier's own stylesheet came back from the toolkit with the
/// components; nothing generates it, so only this test notices if a link is
/// dropped or ordered before the tokens it reads.
#[test]
fn index_html_links_the_app_owned_ontology_stylesheet() {
    let index = fs::read_to_string("index.html").expect("read index.html");
    let sheet = index
        .find("styles/ontology-browser.css")
        .expect("index.html does not link styles/ontology-browser.css, so the ontology \
                 browser renders unstyled");
    let tokens = index.find("styles/vendor/tokens.css").expect("tokens.css link");
    assert!(tokens < sheet, "tokens.css must be linked before ontology-browser.css");
}

/// The ontology stylesheet was split along the same line as the Rust: the
/// toolkit kept the rules for the two components it kept, this repo took the
/// rest. Two copies of `.term-card` would render identically on the day they
/// were created and drift silently afterwards, so assert the halves stay
/// disjoint rather than trusting either side to remember.
#[test]
fn the_vendored_ontology_sheet_carries_no_browser_rules() {
    let vendored =
        fs::read_to_string("styles/vendor/ontology.css").expect("read styles/vendor/ontology.css");
    // Rules only. The toolkit's file header names these same classes in prose,
    // saying where they went — that sentence is the documentation this test
    // exists to keep true, not a violation of it.
    let rules = strip_css_comments(&vendored);
    // One class per component that came back, taken from the selectors each of
    // them emits: iri.rs:82, term_ref.rs:28, term_header.rs:29, term_card.rs,
    // section.rs, selector.rs, browser.rs.
    for class in [
        ".onto-iri",
        ".term-ref",
        ".term-header",
        ".term-card",
        ".onto-section",
        ".ontology-selector",
        ".ontology-browser",
    ] {
        assert!(
            !rules.contains(class),
            "{class} is styled in both the toolkit's ONTOLOGY_CSS and this repo's \
             styles/ontology-browser.css. It belongs to a component that lives here; \
             delete the toolkit's copy."
        );
    }
}

/// Drops `/* ... */` blocks so a selector check reads rules, not prose.
fn strip_css_comments(css: &str) -> String {
    let mut out = String::with_capacity(css.len());
    let mut rest = css;
    while let Some(start) = rest.find("/*") {
        out.push_str(&rest[..start]);
        rest = match rest[start + 2..].find("*/") {
            Some(end) => &rest[start + 2 + end + 2..],
            None => "",
        };
    }
    out.push_str(rest);
    out
}
