//! PAGE · Vocabulary Catalog  (route "/")
//!
//! The DCAT catalog browser: fetches the static `/docs/catalog.jsonld`
//! generated by `pipelines/publish-widoco-docs/generate.py`
//! (`build_catalog_turtle`) and renders one card per published ontology,
//! reusing `edc_web_components::components::DatasetCard` /
//! `edc_web_components::models::DataspaceDataset` — the same presentational
//! components dataspace-rs/edc-web-ui uses to browse a live EDC connector's
//! DCAT catalog — laid out with `patternfly_yew`'s `Gallery`. Each card
//! deep-links to the ontology's term browser at `/ontologies?ontology=<slug>`
//! (see `pages::ontologies`, the former "/" route, now at "/ontologies").
use edc_web_components::components::DatasetCard;
use edc_web_components::models::{Creator, DataspaceDataset, Thumbnail};
use patternfly_yew::prelude::*;
use wasm_bindgen_futures::spawn_local;
use web_sys::window;
use yew::prelude::*;

use crate::components::organisms::{NavRoute, Navbar};
use crate::dcat::{parse_catalog, site_relative, CatalogModel};
use crate::net::fetch_json;

const DOCS_BASE: &str = "/docs";

/// Best-effort parse of an ontology's free-text `owl:versionInfo` as a
/// `semver::Version` — DatasetCard's version badge needs one, but not every
/// ontology declares valid semver (e.g. odrl22 declares plain "2.2"; one
/// leading `.0` short of valid). Falls back to `None` (no badge) rather than
/// showing a mangled/misleading version, e.g. datatourisme's SVN-style
/// "$Date: ...$" string.
fn parse_loose_semver(raw: &str) -> Option<semver::Version> {
    semver::Version::parse(raw).ok().or_else(|| semver::Version::parse(&format!("{raw}.0")).ok())
}

/// A `catalog.jsonld` `foaf:thumbnail`/`dcat:downloadURL`-style IRI (minted
/// under `https://vocab.eona-x.eu/docs/...`) resolved to the actual path
/// this site serves it at, under `DOCS_BASE`.
fn asset_url(iri: &str) -> String {
    format!("{DOCS_BASE}{}", site_relative(iri))
}

#[function_component(CatalogPage)]
pub fn catalog_page() -> Html {
    let catalog = use_state(CatalogModel::default);
    let loading = use_state(|| true);
    let error = use_state(|| None::<String>);

    use_effect_with((), |_| {
        if let Some(doc) = window().and_then(|w| w.document()) {
            doc.set_title("Vocabulary Catalog - EONA-X Vocabularies");
        }
        || ()
    });

    {
        let catalog = catalog.clone();
        let loading = loading.clone();
        let error = error.clone();
        use_effect_with((), move |_| {
            spawn_local(async move {
                match fetch_json::<serde_json::Value>(&format!("{DOCS_BASE}/catalog.jsonld")).await {
                    Ok(doc) => {
                        let model = parse_catalog(&doc);
                        if model.datasets.is_empty() {
                            error.set(Some("No vocabularies have been published yet.".to_string()));
                        }
                        catalog.set(model);
                    }
                    Err(e) => {
                        log::error!("failed to load {DOCS_BASE}/catalog.jsonld: {e}");
                        error.set(Some(
                            "Could not load the vocabulary catalog (/docs/catalog.jsonld). Has the ontology documentation been built?"
                                .to_string(),
                        ));
                    }
                }
                loading.set(false);
            });
            || ()
        });
    }

    let on_navigate = Callback::from(|href: String| {
        if let Some(win) = window() {
            let _ = win.location().set_href(&href);
        }
    });

    html! {
        <main class="eovoc-page">
            <Navbar current={NavRoute::Catalog} />
            <div class="eovoc-page__header">
                <h1 class="eovoc-page__title">{ "Vocabulary Catalog" }</h1>
                <p class="eovoc-page__lede">
                    { (*catalog).description.clone().unwrap_or_else(|| {
                        "Browse the vocabularies and ontologies published by the Eona Vocabulary Hub. Pick one to open its term browser, or download its RDF serialisation directly.".to_string()
                    }) }
                </p>
            </div>

            if *loading {
                <Bullseye>
                    <Spinner size={SpinnerSize::Lg} />
                </Bullseye>
            } else if let Some(msg) = (*error).clone() {
                <Bullseye>
                    <EmptyState title="Unable to load the catalog" icon={Icon::ExclamationCircle}>
                        <div>{ msg }</div>
                    </EmptyState>
                </Bullseye>
            } else {
                <Gallery gutter=true>
                    { for (*catalog).datasets.iter().map(|dataset| {
                        let dataspace_dataset = DataspaceDataset {
                            id: dataset.slug.clone(),
                            title: dataset.title.clone(),
                            version: dataset.version.as_deref().and_then(parse_loose_semver),
                            comment: dataset.description.clone(),
                            thumbnail: dataset.thumbnail.as_deref().map(|iri| Thumbnail { resource: Some(asset_url(iri)) }),
                            creator: dataset.creator.as_ref().map(|c| Creator {
                                name: Some(c.name.clone()),
                                thumbnail: c.thumbnail.as_deref().map(|iri| Thumbnail { resource: Some(asset_url(iri)) }),
                            }),
                            keywords: Vec::new(),
                            policies: Vec::new(),
                            dcterm_types: Vec::new(),
                        };
                        let href = dataset.landing_page.as_deref().map(site_relative)
                            .unwrap_or_else(|| format!("/ontologies?ontology={}", dataset.slug));
                        let on_offer_click = on_navigate.reform(move |()| href.clone());

                        html! {
                            <DatasetCard
                                key={dataset.slug.clone()}
                                dataset={dataspace_dataset}
                                {on_offer_click}
                                button_label="View documentation"
                            />
                        }
                    }) }
                </Gallery>
            }
        </main>
    }
}
