//! PAGE · Vocabulary Catalog  (route "/")
//!
//! The DCAT catalog browser: fetches the static `/docs/catalog.jsonld`
//! generated by `pipelines/publish-widoco-docs/generate.py`
//! (`build_catalog_turtle`) and renders one card per published ontology,
//! rendering one `eona_ui_toolkit::DatasetCard` per published ontology in a
//! plain CSS grid. Each card deep-links to the ontology's term browser at
//! `/ontologies?ontology=<slug>` (see `pages::ontologies`, the former "/"
//! route, now at "/ontologies").
//!
//! This page used to use `edc_web_components::DatasetCard` inside
//! `patternfly_yew`'s `Gallery`. Both are gone: that card is a PatternFly
//! component, so it rendered a second design system's brand inside an EONA-X
//! page and dragged PatternFly's stylesheet, its Font Awesome webfonts and
//! `patternfly-yew` itself into the bundle to do it.
use eona_ui_toolkit::DatasetCard;
use wasm_bindgen_futures::spawn_local;
use web_sys::window;
use yew::prelude::*;

use crate::components::organisms::{NavRoute, Navbar};
use crate::dcat::{parse_catalog, site_relative, CatalogModel, DatasetKind};
use crate::net::fetch_json;

/// Relative to `<base data-trunk-public-url>` — see pages::ontologies.
const DOCS_BASE: &str = "docs";

/// Which `owl:versionInfo` strings are worth showing as a badge.
///
/// The PatternFly card this replaced typed its version as `semver::Version`,
/// so an ontology declaring plain "2.2" (odrl22 — one leading `.0` short of
/// valid semver) silently lost its badge, and this module carried a
/// parse-with-fallback helper to work around it. The toolkit's card takes free
/// text, so the only thing left to filter is the genuinely unshowable:
/// datatourisme publishes an SVN keyword, `"$Date: ... $"`.
fn version_badge(raw: &str) -> Option<AttrValue> {
    let raw = raw.trim();
    if raw.is_empty() || raw.starts_with('$') {
        return None;
    }
    Some(AttrValue::from(raw.to_string()))
}

/// Short badge text for a dataset's `dcterms:type` — `None` for a missing or
/// unrecognised kind, so the caller skips the badge rather than showing raw
/// literal text like "OWL Ontology" that would crowd the thumbnail.
fn kind_badge_label(kind: &DatasetKind) -> Option<&'static str> {
    match kind {
        DatasetKind::Owl => Some("OWL"),
        DatasetKind::Shacl => Some("SHACL"),
        DatasetKind::Crosswalk => Some("CROSSWALK"),
        DatasetKind::Other(_) => None,
    }
}

/// CSS modifier for `DatasetCard`'s badge — one accent colour per kind (see
/// styles/main.css) so the grid is scannable by colour, not just by reading
/// every label.
fn kind_badge_class(kind: &DatasetKind) -> &'static str {
    match kind {
        DatasetKind::Owl => "dataset-card__badge--owl",
        DatasetKind::Shacl => "dataset-card__badge--shacl",
        DatasetKind::Crosswalk => "dataset-card__badge--crosswalk",
        DatasetKind::Other(_) => "",
    }
}

/// A `catalog.jsonld` `foaf:thumbnail`/`dcat:downloadURL`-style IRI (minted
/// under `https://vocab.eona-x.eu/docs/...`) resolved to the actual path
/// this site serves it at, under `DOCS_BASE`.
fn asset_url(iri: &str) -> String {
    format!("{DOCS_BASE}{}", site_relative(iri))
}

#[function_component(CatalogPage)]
pub fn catalog_page() -> Html {
    let catalog = use_state(CatalogModel::default);
    let loading = use_state(|| true);
    let error = use_state(|| None::<String>);

    use_effect_with((), |_| {
        if let Some(doc) = window().and_then(|w| w.document()) {
            doc.set_title("Vocabulary Catalog - EONA-X Vocabularies");
        }
        || ()
    });

    {
        let catalog = catalog.clone();
        let loading = loading.clone();
        let error = error.clone();
        use_effect_with((), move |_| {
            spawn_local(async move {
                match fetch_json::<serde_json::Value>(&format!("{DOCS_BASE}/catalog.jsonld")).await {
                    Ok(doc) => {
                        let model = parse_catalog(&doc);
                        if model.datasets.is_empty() {
                            error.set(Some("No vocabularies have been published yet.".to_string()));
                        }
                        catalog.set(model);
                    }
                    Err(e) => {
                        log::error!("failed to load {DOCS_BASE}/catalog.jsonld: {e}");
                        error.set(Some(
                            "Could not load the vocabulary catalog (/docs/catalog.jsonld). Has the ontology documentation been built?"
                                .to_string(),
                        ));
                    }
                }
                loading.set(false);
            });
            || ()
        });
    }

    html! {
        <main class="eovoc-page">
            <Navbar current={NavRoute::Catalog} />
            <div class="eovoc-page__header">
                <h1 class="eovoc-page__title">{ "Vocabulary Catalog" }</h1>
                <p class="eovoc-page__lede">
                    { (*catalog).description.clone().unwrap_or_else(|| {
                        "Browse the vocabularies and ontologies published by the Eona Vocabulary Hub. Pick one to open its term browser, or download its RDF serialisation directly.".to_string()
                    }) }
                </p>
            </div>

            if *loading {
                <div class="eovoc-state">{ "Loading catalog\u{2026}" }</div>
            } else if let Some(msg) = (*error).clone() {
                <div class="eovoc-state eovoc-state--error">
                    <p class="eovoc-state__title">{ "Unable to load the catalog" }</p>
                    <p class="eovoc-state__message">{ msg }</p>
                </div>
            } else {
                <div class="eovoc-catalog__grid">
                    { for (*catalog).datasets.iter().map(|dataset| {
                        // site_relative's leading "/" is the separator asset_url needs
                        // (DOCS_BASE + site_relative(iri)); trimmed here since this href
                        // is used standalone and must resolve against <base>, not root.
                        let href = dataset.landing_page.as_deref()
                            .map(|iri| site_relative(iri).trim_start_matches('/').to_string())
                            .unwrap_or_else(|| format!("ontologies?ontology={}", dataset.slug));
                        let is_crosswalk = dataset.kind == Some(DatasetKind::Crosswalk);
                        html! {
                            <DatasetCard
                                key={dataset.slug.clone()}
                                title={dataset.title.clone()}
                                {href}
                                description={dataset.description.clone().map(AttrValue::from)}
                                version={dataset.version.as_deref().and_then(version_badge)}
                                publisher={dataset.creator.as_ref().map(|c| AttrValue::from(c.name.clone()))}
                                thumbnail={dataset.thumbnail.as_deref().map(|iri| AttrValue::from(asset_url(iri)))}
                                badge={dataset.kind.as_ref().and_then(kind_badge_label).map(AttrValue::from)}
                                badge_class={dataset.kind.as_ref().map(kind_badge_class).filter(|c| !c.is_empty()).map(AttrValue::from)}
                                action_label={if is_crosswalk { "View 3D crosswalk" } else { "View documentation" }}
                            />
                        }
                    }) }
                </div>
            }
        </main>
    }
}
